version: '3.6'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    ports:
      - '33006:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
